spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
#  resources:
#    cache-period: 3600
  datasource:
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    url: jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8&useSSL=false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
  
logging:
  file: /opt/logs/100003173/apollo-portal.log


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: true
endpoints:
  health:
    sensitive: false

