server:
  port: 8762
  servlet:
    context-path: /
  http2:
    enabled: false
  tomcat:
    accept-count: 100
    max-connections: 200
    min-spare-threads: 15
    max-threads: 200
spring:
  application:
    name: springcloud-gateway
  #  security:
  #    user:
  #      name: "user"
  #      password: "password"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #是否与eureka服务发现组件进行结合
          lowerCaseServiceId: true #使用小写规则，默认大写
          filters:
          - StripPrefix=1
      httpclient:
        connectTimeout: 3000
        pool:
          name: "gateway"

#      routes:
#        - id: springcloud-producer-service
#          uri: lb://springcloud-producer-service
#          order: 10000
#          predicates:
#            - Path=${server.servlet.context-path}/springcloud-producer-service/**
#          filters:
#            - StripPrefix=1
#            - name: Hystrix #熔断
#              args:
#                name: fallbackcmd
#                fallbackUri: forward:/incaseoffailureusethis
#            - name: RateCheck #频率限制
#              args:
#                keyResolver: apiKeyResolver
#        - id: websocket_test
#          uri: ws://localhost:9000
#          order: 9000
#          predicates:
#            - Path=/echo
#          filters:
#            - StripPrefix=1
#            - JwtCheck #jwt校验
#熔断配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000


eureka:
  instance:
    hostname: ${hostname:localhost}
    preferIpAddress: true
    #租期更新时间间隔（默认30秒）
    leaseRenewalIntervalInSeconds: 10
    #租期到期时间（默认90秒）
    leaseExpirationDurationInSeconds: 30
    statusPageUrlPath: /swagger-ui.html
  client:
    serviceUrl:
      # 向每个注册中心注册
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #开启健康检查（需要spring-boot-starter-actuator依赖）
    healthcheck:
      enabled: true
    eurekaServiceUrlPollIntervalSeconds: 60
    # 是否从eureka上获取注册信息
    fetch-registry: true
#  如果项目配置有 server.servlet.context-path 属性，想要被 spring boot admin 监控，就要配置以下属性
#    metadata-map:
#      management:
#        context-path: ${server.servlet.context-path}/actuator
#    health-check-url: http://localhost:${server.port}${server.servlet.context-path}/actuator/health
#    status-page-url: http://localhost:${server.port}${server.servlet.context-path}/actuator/info
#    home-page-url: http://localhost:${server.port}/


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


