aliyun:
  oss:
    endpoint: :http://xxxx.oss-cn-shanghai.aliyuncs.com
    access-key-id:
    access-key-secret:
    client:
      max-connections: 1024
      socket-timeout: 50000
      connection-timeout: 50000
      connection-request-timeout: 3000
      idle-connection-time: 600000
      max-error-retry: 3
      support-cname: true
      sld-enabled: false
      protocol: http
      user-agent: aliyun-sdk-java