server:
  port: 8761
  servlet:
    context-path: /

spring:
  application:
    name: springcloud-eureka
  cloud:
    inetutils:
      #指定使用的网络地址
      preferred-networks: 192.168
eureka:
  instance:
    prefer-ip-address: true
    #  如果项目配置有 server.servlet.context-path 属性，想要被 spring boot admin 监控，就要配置以下属性
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}actuator
    health-check-url: http://localhost:${server.port}${server.servlet.context-path}actuator/health
    status-page-url: http://localhost:${server.port}${server.servlet.context-path}actuator/info
    home-page-url: http://localhost:${server.port}${server.servlet.context-path}
    ip-address: 192.168.0.1
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: true
    # 是否从eureka上获取注册信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    #（设为false，关闭自我保护主要）
    enable-self-preservation: true
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000
  dashboard:
    path: /
    enabled: true

archaius:
  deployment:
    environment: test
logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: true
#
#security:
#  basic:
#    enabled: false